# Generated by Django 4.2.23 on 2025-08-29 19:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=20, validators=[django.core.validators.MinLengthValidator(10)])),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('contact_telephone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('default_shipping_email', models.EmailField(blank=True, max_length=255)),
                ('default_shipping_telephone', models.CharField(blank=True, max_length=20)),
                ('default_shipping_address1', models.TextField(blank=True, max_length=255)),
                ('default_shipping_address2', models.TextField(blank=True, max_length=255)),
                ('default_shipping_city', models.CharField(blank=True, max_length=120)),
                ('default_shipping_postcode', models.CharField(blank=True, max_length=20)),
                ('default_shipping_country', models.CharField(blank=True, max_length=120)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
