# Generated by Django 4.2.23 on 2025-10-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sellerprofile_buyerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='billing_same_as_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='default_billing_address1',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='default_billing_address2',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='default_billing_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='default_billing_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='default_billing_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='default_billing_postcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='default_billing_telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
