# Generated by Django 4.2.23 on 2025-10-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_buyerprofile_billing_same_as_shipping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_manage_staff', 'Can promote/demote staff')]},
        ),
    ]
