# Generated by Django 4.2.23 on 2025-08-29 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'inventories'},
        ),
    ]
