# Generated by Django 4.2.23 on 2025-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_productimage_image_alter_shop_banner'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('shop', 'slug'), name='uniq_product_slug_per_shop'),
        ),
    ]
