# Generated by Django 4.2.23 on 2025-10-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_reviewreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
