# Generated by Django 4.2.23 on 2025-10-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_productreview_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='contact_email_override',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_telephone_override',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='shop',
            name='legal_name_override',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_id_override',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
