# Generated by Django 4.2.23 on 2025-10-12 18:36

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='token',
            field=models.CharField(default=secrets.token_hex, editable=False, max_length=64, unique=True),
        ),
    ]
