# Generated by Django 4.2.23 on 2025-09-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'active'], name='orders_cart_user_id_8e3745_idx'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('user',), name='unique_active_cart_per_user'),
        ),
    ]
