# Generated by Django 4.2.23 on 2025-09-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('completed', 'Completed')], db_index=True, default='pending', help_text='Shipping/fulfilment state (separate from payment status).', max_length=20),
        ),
    ]
